export const HONDURAS_LOCATIONS: Record<string, string[]> = { 
    "Francisco Morazán": ["Tegucigalpa", "Comayagüela", "Valle de Ángeles", "Santa Lucía", "Ojojona"],
  "Cortés": ["San Pedro Sula", "Choloma", "La Lima", "Villanueva", "Puerto Cortés"],
  "Atlántida": ["La Ceiba", "Tela", "El Progreso", "Jutiapa"],
  "Comayagua": ["Comayagua", "Siguatepeque", "La Trinidad"],
  "Santa Bárbara": ["Santa Bárbara", "San Marcos", "Quimistán"],
  "Copán": ["Santa Rosa de Copán", "La Entrada", "Copán Ruinas"],
  "Olancho": ["Juticalpa", "Catacamas", "San Francisco de la Paz"],
  "Choluteca": ["Choluteca", "El Triunfo", "Pespire"],
  "El Paraíso": ["Danlí", "Yuscarán", "El Paraíso"],
  "Yoro": ["Yoro", "El Progreso", "Morazán"],
  "Colón": ["Trujillo", "Tocoa", "Sonaguera"],
  "Ocotepeque": ["Ocotepeque", "Sensenti", "La Labor"],
  "Lempira": ["Gracias", "Erandique", "Lepaera"],
  "Intibucá": ["La Esperanza", "Intibucá", "Yamaranguila"],
  "La Paz": ["La Paz", "Marcala", "Santa Elena"],
  "Valle": ["Nacaome", "San Lorenzo", "Amapala"],
  "Islas de la Bahía": ["Roatán", "Utila", "Guanaja"],
  "Gracias a Dios": ["Puerto Lempira", "Brus Laguna"],
}